CREATE TABLE %1$s (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	CONTENT BLOB(%2$d) NOT NULL,
	CREATEDBY VARCHAR(128) NOT NULL,
	CREATEDON TIMESTAMP NOT NULL,
	DOXID CHAR(32) NOT NULL,
	LASTUPDATEDBY VARCHAR(128) NOT NULL,
	LASTUPDATEDON TIMESTAMP NOT NULL,
	CONTENTVERSION INT NOT NULL,
	ACCESSKEY BLOB(4096),
	VERSION INT NOT NULL,
	PRIMARY KEY (ID)
	);

ALTER TABLE %1$s ADD CONSTRAINT %1$s_DOXID UNIQUE (DOXID);

ALTER TABLE %1$s ADD CONSTRAINT %1$s_IDDOXID UNIQUE (
	ID,
	DOXID
	);

CREATE TABLE %1$sTOMBSTONE (
	ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	CONTENT BLOB(%2$d) NOT NULL,
	CREATEDBY VARCHAR(128) NOT NULL,
	CREATEDON TIMESTAMP NOT NULL,
	DOXID CHAR(32) NOT NULL,
	LASTUPDATEDBY VARCHAR(128) NOT NULL,
	LASTUPDATEDON TIMESTAMP NOT NULL,
	DELETEDBY VARCHAR(128) NOT NULL,
	DELETEDON TIMESTAMP NOT NULL,
	CONTENTVERSION INT NOT NULL,
	PRIMARY KEY (ID)
	);

ALTER TABLE %1$sTOMBSTONE ADD UNIQUE (DOXID);
